version: '3'

services:

  rabbit-mq:
    image: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "BLABLABLA"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672"
        - "6000:15672"

  redis:
    image: redis
    ports:
        - "6379:6379"



  # reviews:
  #   image: hazemsalah/micro_services:reviews_service
  #   # build: 
  #   #   context: ./micro_services/plate
  #   #   dockerfile: Dockerfile
  #   environment:
  #       RABBIT_MQ_SERVICE_HOST: rabbit-mq
        
  #   command:  bash -c "sleep 10; java -jar ./target/Reviews-2.0.1-SNAPSHOT-jar-with-dependencies.jar;"
  #   depends_on:
  #     - rabbit-mq
  #     - server

  # server:
  #   image: hazemsalah/micro_services:server_service 
  #   build: 
  #     context: ./server
  #     dockerfile: Dockerfile
  #   command:  bash -c "sleep 10; java -jar ./target/Server-2.0.1-SNAPSHOT-jar-with-dependencies.jar;"
  #   ports:
  #       - "4000:8080"
  #   depends_on:
  #       - rabbit-mq
  #       - redis
