version: '3'

services:

  rabbit-mq:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "BLABLABLA"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        # - "15672:15672"
        - "6000:6000"

  redis:
    image: redis:alpine
    ports:
        - "6379:6379"



  # reviews:
  #   build: 
  #     context: ./review
  #     dockerfile: Dockerfile
  #   command:  bash -c "sleep 10; java -jar ./target/Reviews-2.0.1-SNAPSHOT-jar-with-dependencies.jar;"
  #   depends_on:
  #     - rabbit-mq
  #     - server

  server:
    # image: hazemsalah/micro_services:server_service 
    build: 
      context: ./server
      dockerfile: Dockerfile
    command:  bash -c "sleep 10; java -jar ./target/Server-2.0.1-SNAPSHOT-jar-with-dependencies.jar;"
    ports:
        - "4000:8080"
    depends_on:
        - rabbit-mq
        - redis
