apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-service
        image: hazemsalah/micro_services:auth_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Auth-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
        imagePullPolicy: Always
      restartPolicy: Always
