apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: controller
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller-service
        image: hazemsalah/micro_services:controller_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Controller-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 9999
        imagePullPolicy: Always
      restartPolicy: Always
