apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-service
        image: hazemsalah/micro_services:database_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Database-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
        imagePullPolicy: Always
      restartPolicy: Always
