apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plates
  labels:
    app: plates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plates
  template:
    metadata:
      labels:
        app: plates
    spec:
      containers:
      - name: plates-service
        image: hazemsalah/micro_services:plates_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq 
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Plates-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
        imagePullPolicy: Always
      restartPolicy: Always
