apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbit-mq
  labels:
    app: mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
      - name: rabbit-mq
        image: rabbitmq:alpine
        env:
          - name: RABBITMQ_DEFAULT_VHOST
            value: /
          - name: RABBITMQ_ERLANG_COOKIE
            value: BLABLABLA
        ports:
        - containerPort: 15672
        - containerPort: 5672
      restartPolicy: Always
