apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews-service
        image: hazemsalah/micro_services:reviews_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq 
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Reviews-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
        imagePullPolicy: Always
      restartPolicy: Always
