apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-service
        image: hazemsalah/micro_services:server_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq 
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Server-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always
