apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-service
        image: hazemsalah/micro_services:users_service
        env:
        - name: RABBIT_MQ_SERVICE_HOST
          value: rabbit-mq 
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Users-2.0.1-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
        imagePullPolicy: Always
      restartPolicy: Always
