# apiVersion: "v1"
# kind: "PersistentVolume"
# metadata:
#   name: postgres-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: fast
#   gcePersistentDisk:
#     pdName: pd-ssd-disk-psql
# ---
#   kind: PersistentVolumeClaim
#   apiVersion: v1
#   metadata:
#     name: psql-persistent-volume-claim
#     annotations:
#       volume.beta.kubernetes.io/storage-class: "fast"
#   spec:
#     accessModes: [ReadWriteOnce]
#     resources:
#       requests:
#         storage: 5Gi
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: postgres-pv
#   labels:
#     type: local
# spec:
#   storageClassName: fast
#   capacity:
#     storage: 100M
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: postgres
#   name: postgres-pv-claim
# spec:
#   storageClassName: fast
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 100M

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M