apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
spec:
  selector:
    app: mq
  ports:
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "5672"
    port: 5672
    targetPort: 5672
